language: php

php:
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

script:
  - php vendor/phpunit/phpunit/phpunit --configuration tests/phpunit.xml tests